### PR TITLE
fix: openAi model names and structure parsing

### LINKED ISSUE #170: createServerFnTool mentioned in README does not exist in the package
### TanStack AI version

0.1.0

### Framework/Library version

React  19.2

### Describe the bug and the steps to reproduce it

The README at [line 82](https://github.com/TanStack/ai/blob/c5df33c2d3e72c3332048ffe7c64a553e5ea86fb/README.md?plain=1#L82) references a function called createServerFnTool from @tanstack/ai-react:

import { createServerFnTool } from '@tanstack/ai-react'

// Define once, get AI tool AND server function (TanStack Start only)
const getProducts = createServerFnTool({
  name: 'getProducts',
  inputSchema: z.object({ query: z.string() }),
  execute: async ({ query }) => db.products.search(query),
})

// Use in AI chat
chat({ tools: [getProducts.server] })

// Call directly from components (no API endpoint needed!)
const products = await getProducts.serverFn({ query: 'laptop' })
However, this function does not appear to exist in the codebase. I searched through the GitHub repository and could not find any implementation of createServerFnTool.

## Questions
Is createServerFnTool planned but not yet implemented?
If it's not available, what is the recommended approach for sharing code between AI tools and TanStack Start server functions?

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

Cursor

### Screenshots or Videos (Optional)

_No response_

### Do you intend to try to help solve this bug with your own PR?

None

### Terms & Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [x] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

### LINKED ISSUE #173: gpt 5 chat model names are incorrect
### TanStack AI version

v0.2.0

### Framework/Library version

hono 1.19.6

### Describe the bug and the steps to reproduce it

Try 
```ts
  const adapter = openaiText("gpt-5.2-chat", {
    apiKey: process.env.OPENAI_API_KEY,
  })
```
but it fails saying the model is not available.

```
>>> chatStream: Fatal error during response creation <<<
>>> Error message: 400 The requested model 'gpt-5.2-chat' does not exist.
>>> Error stack: Error: 400 The requested model 'gpt-5.2-chat' does not exist.
    at APIError.generate (/Users/b/c/flightcontrol2/node_modules/.pnpm/openai@6.15.0_ws@8.17.1_zod@4.2.1/node_modules/openai/src/core/error.ts:72:14)
    at OpenAI.makeStatusError (/Users/b/c/flightcontrol2/node_modules/.pnpm/openai@6.15.0_ws@8.17.1_zod@4.2.1/node_modules/openai/src/client.ts:478:28)
    at OpenAI.makeRequest (/Users/b/c/flightcontrol2/node_modules/.pnpm/openai@6.15.0_ws@8.17.1_zod@4.2.1/node_modules/openai/src/client.ts:728:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
    at async OpenAITextAdapter.chatStream (/Users/b/c/flightcontrol2/node_modules/.pnpm/@tanstack+ai-openai@0.2.0_@tanstack+ai@0.2.0_ws@8.17.1_zod@4.2.1/node_modules/@tanstack/ai-openai/src/adapters/text.ts:109:24)
```

Change to this and it works
```ts
  const adapter = openaiText("gpt-5.2-chat-latest" as "gpt-5.2-chat", {
    apiKey: process.env.OPENAI_API_KEY,
  })
```

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

.

### Screenshots or Videos (Optional)

_No response_

### Do you intend to try to help solve this bug with your own PR?

None

### Terms & Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [x] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

### LINKED ISSUE #178: Unable to assign JSON Schema to toolDefinition
### TanStack AI version

0.2.0

### Framework/Library version

TypeScript, Node

### Describe the bug and the steps to reproduce it

Hi, 

I have come across a small type related issue when assigning JSON Schema to tool definitions via factory function. The issue appears to be caused by the `JSONSchema` type used to constrain `toolDefinition` signature. Reproduction code below.

[Reproduction | Example](https://www.typescriptlang.org/play/?target=99&module=7#code/JYWwDg9gTgLgBAbzjCEA2ARApgM2AO2BmAnzgF84coIQ4ByAARgEN8BnVgYwGsB6FsHoAoYXz5wAtNJmy58hYqXLpYiQGEW7LHACCALjgBRKDShqpKq9ZvzhWAB6RYcAjCxQcLLjoAaAZRgoAgBzRGE4ZABPMCxDek5g-BCRcmEcAFd8LmJSOETQgAoASkMAoNDwyKgsGAyoMiQYGLiGAuT6CmE0rlJOPTgAXmRUTFwCIhJ8QqRxBnKklNd2OHwIeC12YBD8FgAjNB0UaNiGfy4ACywQFgBJfDAM+AAfOCyAE3H8LHf6ADoIq4Hk9zlcboZ2iESgAaQG7ECtei6fIVDqwyKfdhcYJgXL4eLIyH0WHkYqiOa2SlUpQWTTaOAAIUMAHkeBZqRzOaJehx4AyhiN0Ng8IQ8TM4ICCI8YKDrixDE0WvEiRR0asWAiCSjFsTAZjscBcVMtUSSWT2ZzLbZaVodOoWWyKVbnSphKBnPAAFRwLRwABeVBodHofogv25fXg6gFKCFX0mpHFkuBMsucsMfr+kJhcI1iMJqJSav1OLxJsLutJQA)

```typescript
import { toolDefinition } from '@tanstack/ai'

// ---------------------------------------------------------
// Case A: Error
// ---------------------------------------------------------
export interface XString {
  type: 'string'
}
function string(): XString {
  return { type: 'string' }
}
const A = toolDefinition({ // 'XString' is not assignable to type 'SchemaInput | undefined'.
  inputSchema: string(),
  name: 'A string',
  description: 'A string',
})

// ---------------------------------------------------------
// Case B: Ok
// ---------------------------------------------------------

const B = toolDefinition({ 
  inputSchema: { type: 'string' },
  name: 'A string',
  description: 'A string',
})

// ---------------------------------------------------------
// Case C: Ok
// ---------------------------------------------------------
import * as z from 'zod'

const C = toolDefinition({ 
  inputSchema: z.string(),
  name: 'A string',
  description: 'A string',
})
```

The issue appears to be caused by the indexer property on the `JSONSchema` (used for property extension)

https://github.com/TanStack/ai/blob/main/packages/typescript/ai/src/types.ts#L63

```typescript
{
   [key: string]: unknown // Allow additional properties for extensibility
}
```

... where `unknown` can be substituted for `any` to resolve the issue.

```typescript
{
  [key: string]: any // Allow additional properties for extensibility
}
```

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

https://tsplay.dev/wXM3QN

### Screenshots or Videos (Optional)

_No response_

### Do you intend to try to help solve this bug with your own PR?

Maybe, I'll investigate and start debugging

### Terms & Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [x] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

### LINKED ISSUE #186: OpenAI structure output union
### TanStack AI version

0.2.0

### Framework/Library version

vanilla 0.2.0

### Describe the bug and the steps to reproduce it

Structured output doesn't support for unions:

```ts
chat({
  adapter: openaiText("gpt-4o-mini"),
  messages: [{ role: "user", content: "..." }],
  outputSchema: z.object({
    u: z.union([
      z.object({ a: z.string() }), 
      z.object({ b: z.number() })
    ]),
  }),
});

// throw {
//   message: "Invalid schema for response_format 'structured_output': In context=('properties', 'u', 'anyOf', '0'), 'additionalProperties' is required to be supplied and to be false.",
//   type: "invalid_request_error",
//   param: "text.format.schema",
//   code: "invalid_json_schema",
// }
```

The issue seems to come from openAI format converter: https://github.com/TanStack/ai/blob/a8667216fd081be1629f47a531ff3a39052b1156/packages/typescript/ai-openai/src/utils/schema-converter.ts#L48
It doesn't handle the JSON schema `anyOf` object like:
```jsonc
{ 
  "anyOf": [
    // ...
  ]
}
```

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

-

### Screenshots or Videos (Optional)

_No response_

### Do you intend to try to help solve this bug with your own PR?

None

### Terms & Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [x] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

### LINKED ISSUE #187: toServerSentEventsResponse function missing from @tanstack/ai latest package
### TanStack AI version

v0.2.0

### Framework/Library version

React v19.2.3

### Describe the bug and the steps to reproduce it

The `toServerSentEventsResponse` function is documented in the latest documentation and exists in the main branch, but it's not available in the published npm package @tanstack/ai@0.2.0.  
  
Steps to reproduce:  
1. Install @tanstack/ai@0.2.0  
2. Try to import: `import { toServerSentEventsResponse } from "@tanstack/ai"`  
3. Get error: `toServerSentEventsResponse is not exported from @tanstack/ai`  
  
The documentation (updated 2 days ago) shows this function as the recommended way to convert streams to SSE responses, but the npm package (released 4 days ago) doesn't include it.  
  
The function exists in the main branch at `packages/typescript/ai/src/stream-to-response.ts` but wasn't included in the v0.2.0 release.

### Your Minimal, Reproducible Example - (Sandbox Highly Recommended)

https://codesandbox.io/p/devbox/2mmljw?file=%2Fapp%2Fapi%2Fchat%2Froute.ts%3A1%2C16-1%2C42

### Screenshots or Videos (Optional)

Image

### Do you intend to try to help solve this bug with your own PR?

None

### Terms & Code of Conduct

- [x] I agree to follow this project's Code of Conduct
- [x] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

### PR DESCRIPTION
**Pull request by AlemTuzlak**
## 🎯 Changes

Fixes #173 
Fixes #178
Fixes #186
Fixes #187
Fixes #170

## ✅ Checklist

- [ ] I have followed the steps in the [Contributing guide](https://github.com/TanStack/ai/blob/main/CONTRIBUTING.md).
- [ ] I have tested this code locally with `pnpm run test:pr`.

## 🚀 Release Impact

- [ ] This change affects published code, and I have generated a [changeset](https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md).
- [ ] This change is docs/CI/dev-only (no release).

## Summary by CodeRabbit

* **New Features**
  * OpenAI structured-output conversion now supports anyOf unions (oneOf yields a clear error).
  * Exposed updated list of OpenAI chat models.

* **Bug Fixes**
  * Normalized public OpenAI model names to their latest identifiers.

* **Tests**
  * Added unit tests for schema conversion, null handling, unions, and arrays/objects.

* **Documentation**
  * Removed "Bonus: TanStack Start Integration" sections from multiple READMEs.

* **Chores**
  * Added changesets and relaxed JSONSchema index typing for compatibility.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: packages/typescript/ai-openai/src/utils/schema-converter.ts [hunk 1]
```diff
@@ -75,6 +75,12 @@ export function makeOpenAIStructuredOutputCompatible(
             prop.items.required || [],
           ),
         }
+      } else if (prop.anyOf || prop.oneOf) {
```
Comment (hugo082) [inline packages/typescript/ai-openai/src/utils/schema-converter.ts]: Just to notice, `oneOf` is not part of the [open ai supported types](https://platform.openai.com/docs/guides/structured-outputs#supported-types)

Comment (AlemTuzlak) [reply packages/typescript/ai-openai/src/utils/schema-converter.ts]: ah you're right, thank you! Wanted to cover both while I was at it 😓

**Comment by stephansama** [comment]
would it be possible to tack on exporting the chat model names in the main index file?
image
all of the other models are exported except for the chat models

**Comment by AlemTuzlak** [comment]
@stephansama mind opening up an issue? Im off this week and I'll forget this by the time I'm back 😅

**Comment by stephansama** [comment]
> @stephansama mind opening up an issue? Im off this week and I'll forget this by the time I'm back 😅

Of course! I can also make the changes if that is permissible or just create the issue either or both

**Comment by AlemTuzlak** [comment]
@stephansama added the export
